import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type Docker from 'dockerode';
import { describe, expect, it, vi } from 'vitest';
import { DockerOrchestrator } from '../src/orchestrator/docker-adapter.js';
import {
  RuntimeManifestRegistry,
  loadRuntimeManifestRegistry,
  type RuntimeManifest,
} from '../src/orchestrator/runtime-manifests.js';
import type { TraefikRouter } from '../src/orchestrator/traefik-router.js';

const INSTANCE_ID = '77777777-7777-4777-8777-777777777777';
const CHALLENGE_ID = '11111111-1111-4111-8111-111111111111';
const ROUTE_KEY = 'abcdefghijklmnopqrstuvwx12345678';
const IMAGE = `registry.example.test/range/web@sha256:${'a'.repeat(64)}`;

const manifest: RuntimeManifest = {
  challengeId: CHALLENGE_ID,
  image: IMAGE,
  containerPort: 8080,
  user: '65532:65532',
  healthcheck: {
    test: ['CMD', '/app/healthcheck'],
    intervalSeconds: 5,
    timeoutSeconds: 3,
    retries: 5,
    startupSeconds: 5,
  },
  resources: { memoryMb: 128, cpuCores: 0.5, pids: 64, tmpfsMb: 16 },
};

describe('trusted runtime manifests', () => {
  it('accepts pinned images and rejects mutable tags or duplicate challenges', () => {
    expect(new RuntimeManifestRegistry([manifest]).get(CHALLENGE_ID)).toEqual(manifest);
    expect(() => new RuntimeManifestRegistry([{ ...manifest, image: 'nginx:latest' }])).toThrow(
      'Runtime images must use a sha256 digest or image id',
    );
    expect(() => new RuntimeManifestRegistry([manifest, manifest])).toThrow(
      'Duplicate runtime manifest',
    );
  });

  it('loads a UTF-8 BOM manifest generated by Windows tooling', async () => {
    const directory = await mkdtemp(join(tmpdir(), 'cyber-range-manifest-'));
    const path = join(directory, 'runtime-manifests.json');
    try {
      await writeFile(path, `\uFEFF${JSON.stringify([manifest])}`, 'utf8');
      await expect(loadRuntimeManifestRegistry(path)).resolves.toEqual(
        new RuntimeManifestRegistry([manifest]),
      );
    } finally {
      await rm(directory, { recursive: true, force: true });
    }
  });
});

describe('Docker orchestrator', () => {
  it('constructs a restricted target without host ports or control-plane mounts', async () => {
    const fixture = dockerFixture();
    const router = routerFixture();
    const orchestrator = new DockerOrchestrator(fixture.docker, router);

    await expect(orchestrator.spawn(spawnInput())).resolves.toEqual({
      containerId: 'container-id',
      networkId: 'network-id',
    });

    expect(fixture.createNetwork).toHaveBeenCalledWith(expect.objectContaining({
      Internal: true,
      Attachable: false,
    }));
    const options = fixture.createContainer.mock.calls[0]?.[0];
    expect(options).toMatchObject({
      Image: IMAGE,
      User: '65532:65532',
      Env: ['CYBER_RANGE_FLAG=CTF{test-only}'],
      HostConfig: {
        AutoRemove: false,
        CapDrop: ['ALL'],
        Memory: 128 * 1_024 * 1_024,
        MemorySwap: 128 * 1_024 * 1_024,
        NanoCpus: 500_000_000,
        NetworkMode: `crn-${INSTANCE_ID.replaceAll('-', '')}`,
        IpcMode: 'none',
        PidsLimit: 64,
        Privileged: false,
        ReadonlyRootfs: true,
        SecurityOpt: ['no-new-privileges:true', 'apparmor=docker-default'],
        LogConfig: { Type: 'json-file', Config: { 'max-size': '10m', 'max-file': '2' } },
      },
    });
    expect(options?.HostConfig).not.toHaveProperty('PortBindings');
    expect(options?.HostConfig).not.toHaveProperty('Binds');
    expect(options?.HostConfig).not.toHaveProperty('Devices');
    expect(router.upsert).toHaveBeenCalledOnce();
  });

  it('cleans the container and network after a partial start failure', async () => {
    const fixture = dockerFixture({ startError: new Error('start failed') });
    const router = routerFixture();
    const orchestrator = new DockerOrchestrator(fixture.docker, router);

    await expect(orchestrator.spawn(spawnInput())).rejects.toThrow('start failed');
    expect(router.remove).toHaveBeenCalledWith(INSTANCE_ID);
    expect(fixture.containerRemove).toHaveBeenCalledWith({ force: true, v: true });
    expect(fixture.networkRemove).toHaveBeenCalledOnce();
  });

  it('disconnects ingress before removing a network after a partial failure', async () => {
    const fixture = dockerFixture({ startError: new Error('start failed') });
    const orchestrator = new DockerOrchestrator(fixture.docker, routerFixture(), 'traefik');

    await expect(orchestrator.spawn(spawnInput())).rejects.toThrow('start failed');
    expect(fixture.networkDisconnect).toHaveBeenCalledWith({ Container: 'ingress-id', Force: true });
    expect(fixture.networkRemove).toHaveBeenCalledOnce();
  });

  it('reuses a labeled isolated network left by a failed spawn', async () => {
    const fixture = dockerFixture({ existingNetwork: true, ingressAttached: true });
    const orchestrator = new DockerOrchestrator(fixture.docker, routerFixture(), 'traefik');

    await expect(orchestrator.spawn(spawnInput())).resolves.toEqual({
      containerId: 'container-id', networkId: 'network-id',
    });
    expect(fixture.createNetwork).not.toHaveBeenCalled();
    expect(fixture.networkConnect).not.toHaveBeenCalled();
    expect(fixture.createContainer).toHaveBeenCalledOnce();
  });

  it('refuses to reuse a network for another challenge', async () => {
    const fixture = dockerFixture({ existingNetwork: true, managedChallengeId: 'other-challenge' });
    const orchestrator = new DockerOrchestrator(fixture.docker, routerFixture(), 'traefik');

    await expect(orchestrator.spawn(spawnInput())).rejects.toThrow('challenge label');
    expect(fixture.createContainer).not.toHaveBeenCalled();
    expect(fixture.networkRemove).not.toHaveBeenCalled();
  });

  it('fails closed when the Docker host lacks a required isolation control', async () => {
    const fixture = dockerFixture({ securityOptions: ['name=seccomp', 'name=apparmor'] });
    const orchestrator = new DockerOrchestrator(fixture.docker, routerFixture());

    await expect(orchestrator.spawn(spawnInput())).rejects.toThrow(
      'Docker host is missing required userns isolation',
    );
    expect(fixture.createContainer).not.toHaveBeenCalled();
  });

  it('rejects a Docker host with seccomp disabled', async () => {
    const fixture = dockerFixture({ securityOptions: [
      'name=userns', 'name=apparmor', 'name=seccomp,profile=unconfined',
    ] });
    const orchestrator = new DockerOrchestrator(fixture.docker, routerFixture());

    await expect(orchestrator.spawn(spawnInput())).rejects.toThrow('seccomp isolation');
    expect(fixture.createNetwork).not.toHaveBeenCalled();
  });

  it('reports an OOM-killed managed target for automatic cleanup', async () => {
    const fixture = dockerFixture({ existingContainer: true, oomKilled: true });
    const orchestrator = new DockerOrchestrator(fixture.docker, routerFixture());

    await expect(orchestrator.runtimeStatus(INSTANCE_ID)).resolves.toBe('oom');
  });

  it('preflights host isolation, the ingress container, and trusted images', async () => {
    const fixture = dockerFixture();
    const orchestrator = new DockerOrchestrator(fixture.docker, routerFixture(), 'traefik');

    await expect(orchestrator.preflight([manifest])).resolves.toBeUndefined();
    expect(fixture.getContainer).toHaveBeenCalledWith('traefik');
    expect(fixture.getImage).toHaveBeenCalledWith(IMAGE);
  });

  it('rejects a stopped ingress container before any target is created', async () => {
    const fixture = dockerFixture({ ingressRunning: false });
    const orchestrator = new DockerOrchestrator(fixture.docker, routerFixture(), 'traefik');

    await expect(orchestrator.preflight([manifest])).rejects.toThrow(
      'Docker ingress container is not running',
    );
    expect(fixture.createContainer).not.toHaveBeenCalled();
  });

  it('rejects a manifest image that is unavailable on the Docker host', async () => {
    const fixture = dockerFixture({ availableImages: [] });
    const orchestrator = new DockerOrchestrator(fixture.docker, routerFixture(), 'traefik');

    await expect(orchestrator.preflight([manifest])).rejects.toThrow(
      'A trusted runtime image is unavailable on the Docker host',
    );
    expect(fixture.createContainer).not.toHaveBeenCalled();
  });

  it('refuses to delete persisted resource ids without matching ownership labels', async () => {
    const fixture = dockerFixture({ managedInstanceId: '88888888-8888-4888-8888-888888888888' });
    const orchestrator = new DockerOrchestrator(fixture.docker, routerFixture());

    await expect(orchestrator.destroy({
      instanceId: INSTANCE_ID,
      containerId: 'container-id',
      networkId: 'network-id',
    })).rejects.toThrow('without matching ownership labels');
    expect(fixture.containerRemove).not.toHaveBeenCalled();
    expect(fixture.networkRemove).not.toHaveBeenCalled();
  });
});

function spawnInput() {
  return {
    instanceId: INSTANCE_ID,
    challengeId: CHALLENGE_ID,
    routeKey: ROUTE_KEY,
    flag: 'CTF{test-only}',
    manifest,
  };
}

function routerFixture(): TraefikRouter & {
  upsert: ReturnType<typeof vi.fn>;
  remove: ReturnType<typeof vi.fn>;
} {
  return {
    upsert: vi.fn(async () => undefined),
    remove: vi.fn(async () => undefined),
  };
}

function dockerFixture(options: {
  startError?: Error;
  securityOptions?: string[];
  managedInstanceId?: string;
  managedChallengeId?: string;
  existingNetwork?: boolean;
  existingContainer?: boolean;
  oomKilled?: boolean;
  ingressAttached?: boolean;
  ingressRunning?: boolean;
  availableImages?: string[];
} = {}) {
  const containerRemove = vi.fn(async () => undefined);
  const networkRemove = vi.fn(async () => undefined);
  const container = {
    id: 'container-id',
    start: vi.fn(async () => {
      if (options.startError) throw options.startError;
    }),
    stop: vi.fn(async () => undefined),
    remove: containerRemove,
    inspect: vi.fn(async () => ({
      State: {
        Running: options.ingressRunning ?? true,
        OOMKilled: options.oomKilled ?? false,
        Health: { Status: 'healthy' },
      },
      Config: {
        Labels: {
          'cyber-range.managed': 'true',
          'cyber-range.instance-id': options.managedInstanceId ?? INSTANCE_ID,
        },
      },
    })),
  };
  let ingressAttached = options.ingressAttached ?? false;
  const networkConnect = vi.fn(async () => { ingressAttached = true; });
  const networkDisconnect = vi.fn(async () => { ingressAttached = false; });
  const network = {
    id: 'network-id',
    connect: networkConnect,
    disconnect: networkDisconnect,
    remove: networkRemove,
    inspect: vi.fn(async () => ({
      Internal: true,
      Attachable: false,
      Containers: ingressAttached ? { 'ingress-id': { Name: 'traefik' } } : {},
      Labels: {
        'cyber-range.managed': 'true',
        'cyber-range.instance-id': options.managedInstanceId ?? INSTANCE_ID,
        'cyber-range.challenge-id': options.managedChallengeId ?? CHALLENGE_ID,
      },
    })),
  };
  const createContainer = vi.fn(async (_options: Docker.ContainerCreateOptions) => container);
  const createNetwork = vi.fn(async (_options: Docker.NetworkCreateOptions) => network);
  const getContainer = vi.fn(() => container);
  const getImage = vi.fn((image: string) => ({
    inspect: vi.fn(async () => {
      if (options.availableImages && !options.availableImages.includes(image)) {
        throw { statusCode: 404 };
      }
      return { Id: 'image-id' };
    }),
  }));
  const docker = {
    info: vi.fn(async () => ({
      SecurityOptions: options.securityOptions ?? [
        'name=userns',
        'name=seccomp,profile=default',
        'name=apparmor',
      ],
    })),
    listContainers: vi.fn(async () => options.existingContainer ? [{ Id: 'container-id' }] : []),
    listNetworks: vi.fn(async () => options.existingNetwork ? [{ Id: 'network-id' }] : []),
    createContainer,
    createNetwork,
    getContainer,
    getNetwork: vi.fn(() => network),
    getImage,
  };
  return {
    docker: docker as unknown as Docker,
    createContainer,
    createNetwork,
    getContainer,
    getImage,
    containerRemove,
    networkRemove,
    networkConnect,
    networkDisconnect,
  };
}
